name: Open PR when a github issue with the subject "incident report" is opened
on:
  issues:
    types:
      - opened
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Incident Report
          title: Incident Report
          body: Credit new Incident Report
          branch: incident-report