name: Open PR when a github issue with the subject "incident report" is opened
on:
  issues:
    types:
      - opened
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
